"""Adiciona status de subscrição e gamificação ao User

Revision ID: 1ac726dffd62
Revises: b0c92a1cbef2
Create Date: 2025-10-20 13:46:26.836686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac726dffd62'
down_revision = 'b0c92a1cbef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=30), server_default='free', nullable=False))
        batch_op.add_column(sa.Column('subscription_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('watering_streak', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('watering_streak')
        batch_op.drop_column('subscription_expires_at')
        batch_op.drop_column('subscription_status')

    # ### end Alembic commands ###
