"""Adiciona tracked_watering à tabela UserPlant

Revision ID: 98566b09eec7
Revises: b57f78fe52fc
Create Date: 2025-10-20 10:38:40.842043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98566b09eec7'
down_revision = 'b57f78fe52fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_garden', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracked_watering', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_garden', schema=None) as batch_op:
        batch_op.drop_column('tracked_watering')

    # ### end Alembic commands ###
