"""Adiciona health_cache à PlantGuide

Revision ID: 9b77a0c82b3c
Revises: a7e988b0da8f
Create Date: 2025-10-29 20:55:51.742891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b77a0c82b3c'
down_revision = 'a7e988b0da8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_guide', schema=None) as batch_op:
        batch_op.add_column(sa.Column('health_cache', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_guide', schema=None) as batch_op:
        batch_op.drop_column('health_cache')

    # ### end Alembic commands ###
