"""Adiciona primary_image_url à UserPlant

Revision ID: a7e988b0da8f
Revises: 1ac726dffd62
Create Date: 2025-10-29 20:18:25.926731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e988b0da8f'
down_revision = '1ac726dffd62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_garden', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_image_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_garden', schema=None) as batch_op:
        batch_op.drop_column('primary_image_url')

    # ### end Alembic commands ###
