"""Adiciona fcm_token_updated_at à tabela User

Revision ID: b0c92a1cbef2
Revises: 98566b09eec7
Create Date: 2025-10-20 13:45:11.028222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c92a1cbef2'
down_revision = '98566b09eec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fcm_token_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('fcm_token_updated_at')

    # ### end Alembic commands ###
