"""Adiciona fcm_token à tabela User

Revision ID: b57f78fe52fc
Revises: b5aac393c1cd
Create Date: 2025-10-20 09:47:15.687568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57f78fe52fc'
down_revision = 'b5aac393c1cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fcm_token', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('fcm_token')

    # ### end Alembic commands ###
