"""Criação inicial das tabelas users, plant_guide e user_garden

Revision ID: b5aac393c1cd
Revises: 
Create Date: 2025-10-16 20:46:45.996330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5aac393c1cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_guide',
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('scientific_name', sa.String(length=150), nullable=False),
    sa.Column('last_gemini_update', sa.DateTime(), nullable=True),
    sa.Column('details_cache', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nutritional_cache', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_garden',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('last_watered', sa.DateTime(), nullable=True),
    sa.Column('care_notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plant_entity_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['plant_entity_id'], ['plant_guide.entity_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_garden')
    op.drop_table('users')
    op.drop_table('plant_guide')
    # ### end Alembic commands ###
