"""Adiciona campos de perfil (bio, foto, local) ao User

Revision ID: f619704e6916
Revises: 9b77a0c82b3c
Create Date: 2025-10-30 09:26:52.082388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f619704e6916'
down_revision = '9b77a0c82b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('country')
        batch_op.drop_column('profile_picture_url')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
